-- ODAOS Database User Setup Script
-- Run this as SYSDBA on the BRMPDB container

-- Connect to the PDB first
ALTER SESSION SET CONTAINER = BRMPDB;

-- Create the ODAOS user
CREATE USER ODAOS_USER IDENTIFIED BY "OdaosSecure#2026"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

-- Grant necessary privileges for monitoring (read-only access)
GRANT CREATE SESSION TO ODAOS_USER;

-- Performance monitoring views
GRANT SELECT ON V_$SYSSTAT TO ODAOS_USER;
GRANT SELECT ON V_$SQL TO ODAOS_USER;
GRANT SELECT ON V_$SQLAREA TO ODAOS_USER;
GRANT SELECT ON V_$SESSION TO ODAOS_USER;
GRANT SELECT ON V_$SYSTEM_EVENT TO ODAOS_USER;
GRANT SELECT ON V_$SGAINFO TO ODAOS_USER;
GRANT SELECT ON V_$PARAMETER TO ODAOS_USER;
GRANT SELECT ON V_$INSTANCE TO ODAOS_USER;
GRANT SELECT ON V_$VERSION TO ODAOS_USER;
GRANT SELECT ON V_$DATABASE TO ODAOS_USER;

-- Tablespace monitoring
GRANT SELECT ON DBA_TABLESPACES TO ODAOS_USER;
GRANT SELECT ON DBA_DATA_FILES TO ODAOS_USER;
GRANT SELECT ON DBA_FREE_SPACE TO ODAOS_USER;

-- Blocking session detection
GRANT SELECT ON V_$LOCKED_OBJECT TO ODAOS_USER;
GRANT SELECT ON DBA_OBJECTS TO ODAOS_USER;

-- Alert log access (if available)
GRANT SELECT ON V_$DIAG_ALERT_EXT TO ODAOS_USER;

-- Resource limits
GRANT SELECT ON V_$RESOURCE_LIMIT TO ODAOS_USER;

-- PDB information
GRANT SELECT ON V_$PDBS TO ODAOS_USER;

-- Optional: ASM info (if using ASM)
-- GRANT SELECT ON V_$ASM_DISKGROUP TO ODAOS_USER;

COMMIT;

-- Verify grants
SELECT PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE = 'ODAOS_USER';
SELECT TABLE_NAME FROM DBA_TAB_PRIVS WHERE GRANTEE = 'ODAOS_USER';

-- Connection test
-- sqlplus ODAOS_USER/OdaosSecure#2026@localhost:1521/brmpdb.dbsubnet.brmdevvcn.oraclevcn.com
